# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/vcu118mig.xci
# IP: The module: 'vcu118mig' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu118mig_microblaze_mcs || ORIG_REF_NAME==vcu118mig_microblaze_mcs}]

# Block Designs: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/bd_28a7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7 || ORIG_REF_NAME==bd_28a7}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_microblaze_I_0 || ORIG_REF_NAME==bd_28a7_microblaze_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_0 || ORIG_REF_NAME==bd_28a7_ilmb_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_0 || ORIG_REF_NAME==bd_28a7_dlmb_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_4/bd_28a7_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_dlmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_5/bd_28a7_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_ilmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_6/bd_28a7_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_lmb_bram_I_0 || ORIG_REF_NAME==bd_28a7_lmb_bram_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_7/bd_28a7_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_second_dlmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_8/bd_28a7_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_second_ilmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_9/bd_28a7_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_28a7_second_lmb_bram_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_iomodule_0_0 || ORIG_REF_NAME==bd_28a7_iomodule_0_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_1/vcu118mig_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu118mig_phy || ORIG_REF_NAME==vcu118mig_phy}]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_microblaze_I_0 || ORIG_REF_NAME==bd_28a7_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0_ooc_debug.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_0 || ORIG_REF_NAME==bd_28a7_ilmb_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_0 || ORIG_REF_NAME==bd_28a7_dlmb_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_4/bd_28a7_dlmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_5/bd_28a7_ilmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_6/bd_28a7_lmb_bram_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_7/bd_28a7_second_dlmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_8/bd_28a7_second_ilmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_9/bd_28a7_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_iomodule_0_0 || ORIG_REF_NAME==bd_28a7_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/bd_28a7_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu118mig_microblaze_mcs || ORIG_REF_NAME==vcu118mig_microblaze_mcs}] {/inst }]/inst ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_1/par/vcu118mig_phy_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/vcu118mig_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu118mig'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/par/vcu118mig.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu118mig'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/vcu118mig.xci
# IP: The module: 'vcu118mig' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu118mig_microblaze_mcs || ORIG_REF_NAME==vcu118mig_microblaze_mcs}]

# Block Designs: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/bd_28a7.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7 || ORIG_REF_NAME==bd_28a7}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_microblaze_I_0 || ORIG_REF_NAME==bd_28a7_microblaze_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_0 || ORIG_REF_NAME==bd_28a7_ilmb_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_0 || ORIG_REF_NAME==bd_28a7_dlmb_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_4/bd_28a7_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_dlmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_5/bd_28a7_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_ilmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_6/bd_28a7_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_lmb_bram_I_0 || ORIG_REF_NAME==bd_28a7_lmb_bram_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_7/bd_28a7_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_second_dlmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_8/bd_28a7_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_28a7_second_ilmb_cntlr_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_9/bd_28a7_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_28a7_second_lmb_bram_I_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_28a7_iomodule_0_0 || ORIG_REF_NAME==bd_28a7_iomodule_0_0}]

# IP: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_1/vcu118mig_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu118mig_phy || ORIG_REF_NAME==vcu118mig_phy}]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_microblaze_I_0 || ORIG_REF_NAME==bd_28a7_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0_ooc_debug.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_0/bd_28a7_microblaze_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_rst_0_0 || ORIG_REF_NAME==bd_28a7_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_1/bd_28a7_rst_0_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_ilmb_0 || ORIG_REF_NAME==bd_28a7_ilmb_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_2/bd_28a7_ilmb_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_dlmb_0 || ORIG_REF_NAME==bd_28a7_dlmb_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_3/bd_28a7_dlmb_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_4/bd_28a7_dlmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_5/bd_28a7_ilmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_6/bd_28a7_lmb_bram_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_7/bd_28a7_second_dlmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_8/bd_28a7_second_ilmb_cntlr_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_9/bd_28a7_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_28a7_iomodule_0_0 || ORIG_REF_NAME==bd_28a7_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/ip/ip_10/bd_28a7_iomodule_0_0_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/bd_0/bd_28a7_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu118mig_microblaze_mcs || ORIG_REF_NAME==vcu118mig_microblaze_mcs}] {/inst }]/inst ]]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_0/vcu118mig_microblaze_mcs_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/ip_1/par/vcu118mig_phy_ooc.xdc

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/vcu118mig_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu118mig'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yang/vcu118/vcu118.srcs/sources_1/ip/vcu118mig/par/vcu118mig.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu118mig'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
